name: Criação de repositório automatizado.

on:
  issues:
    types: [opened, reopened]
    

jobs:
  add-comment:
  runs-on: ubuntu-latest
  steps:
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Acompanhe através do link https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
        reactions: '+1'
        
  form-to-json:
    name: Convert Form Issue to JSON
    runs-on: ubuntu-latest
    needs: [add-comment]
    outputs:
      payload
  
  
