name: Criação de repositório automatizado.

on:
  issues:
    types: [opened, reopened]
    workflow_dispatch:
      inputs:
        template:
          description: 'Issue Template'
          required: true
          # Filtrar pelo nome do template customizado utilizado
          default: 'Criação de repositório'
    

jobs:
  add-comment:
    name: Add Comment on Issue
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2

        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Acompanhe através do link https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          reactions: '+1'

        
  form-to-json:
    name: Convert Form Issue to JSON
    runs-on: ubuntu-latest
    needs: [add-comment]
    outputs:
      payload-parsed: ${{ steps.payload.outputs.json_var }}
    steps:
      
          
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v3
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
          
      - name: Set output script
        id: payload
        uses: actions/github-script@v6
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = ${{ steps.parse.outputs.payload }}
            const template = payload.Template.split('\r\r')[0]
            
            core.setCommandEcho(true)
            core.setOutput('json_var',payload)
            core.setCommandEcho(false)
  create-github-repo:
    uses: rafaishida/reusable-workflows/.github/workflows/create-repo.yml@v7
    needs: 
      - form-to-json
    with: 
      payload: ${{ needs.form-to-json.outputs.payload-parsed }}
    secrets: inherit
    
  commit-modules-into-repo:
    name: Commit Modules into Repo
    runs-on: ubuntu-latest
    
    needs: 
      - form-to-json
      - create-github-repo
    outputs:
      recurso: ${{ needs.create-github-repo.outputs.repo_name }}
      repo_name: ${{ needs.create-github-repo.outputs.repo_name }}
      #contas: ${{ needs.create-github-repo.outputs.repo_name }}
    steps:

      - name: Checkout Modulo
        uses: actions/checkout@v3
        with: 
          repository: rafaishida/lambda-template
          ref: 'refs/heads/main'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Repo Files
        run:
          mkdir ..infra
          cp -R ./infra/* ../infra
          cp -R .README.md ../
          ls -R ../infra
          
      - name: Chechout Repo Criado
        uses: actions/checkout@v3
        with: 
          repository: rafaishida/${{ needs.create-github-repo.outputs.repo_name }}
          path: ./
          ref: 'refs/heads/main'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Criar novo repositório vazio
        uses: actions/create-repository@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: rafaishida/${{ needs.create-github-repo.outputs.repo_name }}
             
          

    
         
          
  add-error-comment:
    name: Add Error comment
    runs-on: ubuntu-latest
    if: |
      (needs.create-github-repo.result == 'failure')
    needs: [create-github-repo]
    steps: 
      - name: Create comment
        uses: peter-evans/create-or-update-comments@v2
        with:
          issue-number: ${{ github.event.issue.number}}
          body: |
            Erro durante a exeucução.Acesse o link https://github.com/rafaishida/${{needs.create-github-repo.outputs.repo_name}}
          reactions: '+1'
          
  auto-closing-issue:
    name: Auto-closing Issue
    runs-on: ubuntu-latest
    if: |
      always() &&
      (needs.create-github-repo.result == 'success')
    needs: [create-github-repo]
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with: 
          issue-number: ${{ github.event.issue.number }}
          body: |
            Sucesso na criação do repo.Repo criado https://github.com/rafaishida/${{needs.create-github-repo.outputs.repo_name}}
          reactions: '+1'

      - name: Close Issue
        id: parse
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Fechando issue automaticamente
            
